# Generated by Django 4.0.2 on 2022-02-17 13:05

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='body',
            field=tinymce.models.HTMLField(),
        ),
    ]
