# Generated by Django 4.0.2 on 2022-02-17 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_menu_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='body',
            field=models.TextField(null=True),
        ),
    ]
